### ISSUE TITLE
AMap3DMap 升级到5.0.0 之后路线记录有问题

### ISSUE THREAD

**Issue by Beyond-Chao** [hadesh/iOS_3D_RecordPath#2]
AMap3DMap 升级到5.0.0 之后，MAOverlayRenderer类 的 referenceDidChange 废弃了，
导致路径可以记录，但画出来的路径，随地图一起移动，没有固定，怎么破？

**Comment by hadesh** [comment]
5.0.0后升级为opengl es2.0了，使用方式有所改变。请参考 https://github.com/amap-demo/iOS-path-record  这个。
